config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #dashboard
  get "/dashboard" => "accounts#index"
  get "profile/:username" => "accounts#profile", as: :profile

  resources :posts, only: [:new,:show,:create]
  root to: "public#homepage"

  get '/user' => "accounts#index", :as => :user_root
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :image, ImageUploader
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]
  def full_name
    "#{first_name} #{last_name}"
  end

  def total_followers
    0
  end

  def total_following
    0
  end

  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  validate :validate_username

def validate_username
  if Account.where(email: username).exists?
    errors.add(:username, :invalid)
  end
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader

    scope :active, -> { where active: true }
    belongs_to :account
    before_create :set_active
    def set_active
        self.active = true
    end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    before_action :authenticate_account!
    before_action :set_account, only: [:profile]

    def index
        # user dashboard - post feed
        @posts = Post.active

    end

    def profile
        @posts = @account.posts.active
        # user profile
    end

    def set_account
        @account = Account.find_by_username(params[:username])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :image, :image_cache, :email, :description, :website])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :image, :image_cache, :email, :description, :website])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :password])
    end

    def after_sign_in_path_for(resource)
      dashboard_path
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def show
    end

    def create
        @post = Post.new(post_params)
        @post.account_id = current_account.id if account_signed_in?

        if @post.save
            redirect_to dashboard_path, flash: { success: "Post was created successfully!"}
        else
            redirect_to new_post_path, flash: { success: "Post was not saved!"}
        end
    end

    def new
        @post = Post.new
    end


    private

    def post_params
        params.require(:post).permit(:image, :image_cache)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
    helper_method :resource_name, :resource, :devise_mapping, :resource_class

    def resource_name
      :account
    end

    def resource
      @resource ||= Account.new
    end

    def resource_class
      Account
    end

    def devise_mapping
      @devise_mapping ||= Devise.mappings[:account]
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/accounts/index.html.erb
<div class="container">
<div class="row">
<div class="col-8">
<% @posts.each do |post| %>
    <div class="insta-post">
<div class="meta-post">
<%= link_to image_tag(post.account.image.thumb_post.url, class: "img-circle profile-pic-post") , profile_path(post.account.username) %>
<%= link_to post.account.username, profile_path(post.account.username), class: "username-link" %>
</div>
<%= image_tag post.image.url, class: "img img-fluid" %>
</div>
<% end %>
</div>
<div class="col-4">
<div class="account-summary">
<p><strong><%= current_account.username %></strong> </br>
<%= current_account.full_name %></p>
</div>
<div class="account-suggestion">
</div>
</div>
</div>
</div>

app/views/accounts/profile.html.erb
<div class="container">
<div class="row">
<div class="col-4">
    <% if @account.image? %>
<%= image_tag @account.image.thumb_profile.url, class: "profile-pic img-circle", size: "200px" %>
<% end %>
</div>
<div class="col-8">
<h1><%= @account.full_name %></h1>
<%= link_to "Edit Profile", edit_account_registration_path, class: "btn btn-secondary" %>
<div class="profile-stats"><%= @account.posts.size %> posts</div>
<div class="profile-stats"><%= @account.total_followers %> followers</div>
<div class="profile-stats"><%= @account.total_following %> following</div>

<p><%= @account.username %></p>
<p><%= simple_format @account.description if @account.description.present? %></p>
<p><%= link_to "#{@account.website}", @account.website if @account.website.present? %></p>
</div>
</div>

<div class="row profile-posts">
<% @posts.each do |post| %>
    <div class="col-4">
    <div class="insta-post">
<%= image_tag post.image.url, class: "img img-fluid" %>
</div>
</div>
<% end %>
</div>
</div>

app/views/layouts/_account_nav.html.erb
<li class="nav-item">
<%= link_to "Dashboard", dashboard_path, class: "nav-link active" %>
</li>
<li class="nav-item">
<%= link_to "New Post", new_post_path, class: "nav-link active" %>
</li>
<li class="nav-item">
<%= link_to "My Profile", profile_path(current_account.username), class: "nav-link active" %>
</li>
<li class="nav-item">
<%= link_to "Sign Out", destroy_account_session_path, :method => :delete, class: "nav-link active" %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
        <title>Instagram Clone</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', "data-turbolinks": false %>
    </head>

  <body>
                    <% if account_signed_in? %>
<%= render "layouts/account_nav" %>
<% end %>

        <div class>
            <%= yield %>
            </div>
        </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>

      <label>Images</label>
      <%= f.file_field :image, class: "form-control" %>
      <%= f.hidden_field :image_cache %>
      <%= f.submit "Save Post", class: "btn btn-success" %>
  <% end %>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render "form" %>